#!/bin/sh

SOURCE_DIR=$( dirname "$0" )
DIR=$( cd "$SOURCE_DIR" && pwd )

. $DIR/common.sh

CORE_NAME=$1
CRAWLDB_DIR=${CORES_HOME}/${CORE_NAME}/crawldb/crawldb
NUTCH_HOME=${CORES_HOME}/${CORE_NAME}/apache-nutch/

if [ ! -e $CRAWLDB_DIR ]; then
    mkdir -p $CRAWLDB_DIR
fi

check_params ${CORE_NAME}
initialize $CORE_NAME $CRAWLDB_DIR $NUTCH_HOME

$NUTCH_HOME/bin/crawl $NUTCH_HOME/urls/ ${CORES_HOME}/${CORE_NAME}/crawldb/ http://localhost:8080/solr/${CORE_NAME}/ 20
