#!/bin/sh

export JAVA_HOME=$(readlink -f /usr/bin/java | sed "s:bin/java::")

if [ "$1" = "" ]; then
    echo "You must provide the core name (ex: ./crawl core_name)"
else
    NUTCH_HOME=$HOME/apache-nutch-$1/
    $NUTCH_HOME/bin/crawl $NUTCH_HOME/urls/ $HOME/crawl-$1/ http://localhost:8080/solr/$1/ 20
fi;
