#!/bin/sh

CORE_NAME=$1
CRAWLDB_DIR=${HOME}/crawl-${CORE_NAME}/crawldb
NUTCH_HOME=${HOME}/apache-nutch-${CORE_NAME}/

SOURCE_DIR=$( dirname "$0" )
DIR=$( cd "$SOURCE_DIR" && pwd )

. $DIR/common.sh
check_params $1
initialize $CORE_NAME $CRAWLDB_DIR $NUTCH_HOME

$NUTCH_HOME/bin/crawl $NUTCH_HOME/urls/ $HOME/crawl-$1/ http://localhost:8080/solr/$1/ 20
