#!/bin/sh

SOURCE_DIR=$( dirname "$0" )
DIR=$( cd "$SOURCE_DIR" && pwd )

. $DIR/common.sh

CORE_NAME=$1

if [ "$1" = "" ]; then
    echo "You must provide the core name (ex: ./deleteCrawl core_name)"
else
    rm -rf ${CORES_HOME}/${CORE_NAME}/crawldb
fi;
