#!/bin/sh

if [ "$1" = "" ]; then
    echo "You must provide the core name (ex: ./deleteIndex core_name)"
else
    curl -s http://localhost:8080/solr/$1/update?commit=true --data '<delete><query>*:*</query></delete>' -H 'Content-type:text/xml; charset=utf-8'
fi;
