#!/bin/sh

CORE_NAME=$1
CRAWLDB_DIR=${HOME}/crawl-${CORE_NAME}/crawldb
NUTCH_HOME=${HOME}/apache-nutch-${CORE_NAME}/

SOURCE_DIR=$( dirname "$0" )
DIR=$( cd "$SOURCE_DIR" && pwd )


. $DIR/common.sh
check_params $CORE_NAME
if [ "$2" = "" ]; then
    echo "You must provide the status (db_unfetched, db_fetched, db_redir_temp, db_redir_perm or db_duplicate)"
    exit 1
fi
initialize $CORE_NAME $CRAWLDB_DIR $NUTCH_HOME

OUT_DIR=`mktemp -d`
echo "Output directory is $OUT_DIR"
$NUTCH_HOME/bin/nutch readdb $CRAWLDB_DIR -dump $OUT_DIR/dump -status $2
cat $OUT_DIR/dump/* | grep -e "^http://" | sed -e "s/ *Version: [0-9] *$//g" | sed -e "s/\(:\|\/\|\.\|\-\|\+\|\?\)/\\\\\1/g"
rm -rf $OUT_DIR
