#!/bin/sh

SOURCE_DIR=$( dirname "$0" )
DIR=$( cd "$SOURCE_DIR" && pwd )

. $DIR/common.sh

CORE_NAME=$1

check_params ${CORE_NAME}

SEGMENTS_DIR=${CORES_HOME}/${CORE_NAME}/crawldb/segments
REQUIRED_DIRS="crawl_fetch crawl_parse parse_data parse_text"

if [ -e $SEGMENTS_DIR ]; then
    SEGMENT_DIRS=$( find $SEGMENTS_DIR -maxdepth 1 -type d -not -path $SEGMENTS_DIR )
    for SEGMENT_DIR in $SEGMENT_DIRS
    do
        for REQUIRED_DIR in $REQUIRED_DIRS
        do
            if [ ! -e "${SEGMENT_DIR}/${REQUIRED_DIR}" ]; then
                echo "Removing corrupted segment: ${SEGMENT_DIR} (missing ${REQUIRED_DIR})"
                rm -rf "${SEGMENT_DIR}"
                break
            fi
        done
    done
fi
