#!/bin/sh

if [ "$1" = "" ]; then
    echo "You must provide the core name (ex: ./optimizeIndex core_name)"
else
    curl -s http://localhost:8080/solr/$1/update --data '<optimize/>' -H 'Content-type:text/xml; charset=utf-8'
fi;
