#!/bin/sh

SOURCE_DIR=$( dirname "$0" )
DIR=$( cd "$SOURCE_DIR" && pwd )

. $DIR/common.sh
check_params $1

curl -s http://localhost:8080/solr/$1/update --data '<optimize/>' -H 'Content-type:text/xml; charset=utf-8'
