#!/bin/sh

CORE_NAME=$1
CRAWLDB_DIR=${HOME}/crawl-${CORE_NAME}/crawldb
NUTCH_HOME=${HOME}/apache-nutch-${CORE_NAME}/

SOURCE_DIR=$( dirname "$0" )
DIR=$( cd "$SOURCE_DIR" && pwd )

. $DIR/common.sh
check_params $1
initialize $CORE_NAME $CRAWLDB_DIR $NUTCH_HOME

SCRIPTS_DIR=`dirname "${0}"`
OPTIMIZE_INDEX_SCRIPT=$SCRIPTS_DIR/optimizeIndex
$NUTCH_HOME/bin/nutch solrindex http://localhost:8080/solr/$1/ $HOME/crawl-$1/crawldb/ -linkdb $HOME/crawl-$1/linkdb/ -dir $HOME/crawl-$1/segments/
RET_CODE=$?
if [ $RET_CODE -ne 0 ]; then
    exit $RET_CODE
fi
$OPTIMIZE_INDEX_SCRIPT $1
