#!/bin/sh

SOURCE_DIR=$( dirname "$0" )
DIR=$( cd "$SOURCE_DIR" && pwd )

. $DIR/common.sh

CORE_NAME=$1
CRAWLDB_DIR=${CORES_HOME}/${CORE_NAME}/crawldb
NUTCH_HOME=${CORES_HOME}/${CORE_NAME}/apache-nutch

check_params $1
initialize $CORE_NAME $CRAWLDB_DIR $NUTCH_HOME

SCRIPTS_DIR=`dirname "${0}"`
DELETE_INDEX_SCRIPT=$SCRIPTS_DIR/deleteIndex
OPTIMIZE_INDEX_SCRIPT=$SCRIPTS_DIR/optimizeIndex

$DELETE_INDEX_SCRIPT $1
$NUTCH_HOME/bin/nutch solrindex http://localhost:8080/solr/$1/ $HOME/crawl-$1/crawldb/ -linkdb $HOME/crawl-$1/linkdb/ -dir $HOME/crawl-$1/segments/
RET_CODE=$?
if [ $RET_CODE -ne 0 ]; then
    exit $RET_CODE
fi
$OPTIMIZE_INDEX_SCRIPT $1
