#!/bin/sh

export JAVA_HOME=$(readlink -f /usr/bin/java | sed "s:bin/java::")

if [ "$1" = "" ]; then
    echo "You must provide the core name (ex: ./crawl core_name)"
else
    NUTCH_HOME=$HOME/apache-nutch-1.8-$1/
    if [ "$2" = "" ]; then
        $NUTCH_HOME/bin/nutch readdb $HOME/crawl-$1/crawldb -stats
    else
        $NUTCH_HOME/bin/nutch readdb $HOME/crawl-$1/crawldb -url $2
    fi
fi
