#!/bin/sh

CORE_NAME=$1
CRAWLDB_DIR=${HOME}/crawl-${CORE_NAME}/crawldb
NUTCH_HOME=${HOME}/apache-nutch-${CORE_NAME}/

SOURCE_DIR=$( dirname "$0" )
DIR=$( cd "$SOURCE_DIR" && pwd )

. $DIR/common.sh
check_params $CORE_NAME
initialize $CORE_NAME $CRAWLDB_DIR $NUTCH_HOME

if [ "$2" = "" ]; then
    $NUTCH_HOME/bin/nutch readdb $CRAWLDB_DIR -stats
else
    $NUTCH_HOME/bin/nutch readdb $CRAWLDB_DIR -url $2
fi
