#!/bin/sh

SOURCE_DIR=$( dirname "$0" )
DIR=$( cd "$SOURCE_DIR" && pwd )

. $DIR/common.sh

CORE_NAME=$1
CRAWLDB_DIR=${CORES_HOME}/${CORE_NAME}/crawldb/crawldb
NUTCH_HOME=${CORES_HOME}/${CORE_NAME}/apache-nutch

check_params $CORE_NAME
initialize $CORE_NAME $CRAWLDB_DIR $NUTCH_HOME

if [ "$2" = "" ]; then
    $NUTCH_HOME/bin/nutch readdb $CRAWLDB_DIR -stats
else
    $NUTCH_HOME/bin/nutch readdb $CRAWLDB_DIR -url $2
fi
